-- =============================================================================
-- Teyvat / Travel Eye Sri Lanka — content seed
-- =============================================================================
-- GENERATED FILE — do not edit by hand.
-- Regenerate with:  npm run seed:generate
-- Source of truth:  scripts/fixtures/*.ts (the original approved demo content)
--
-- Safe to re-run: every statement is an upsert keyed on the slug id, so this
-- restores the approved baseline content without duplicating rows.
-- =============================================================================

begin;

-- 20 row(s) -> public.destinations
insert into public.destinations (id, name, latitude, longitude, region, province, category, short_description, long_description, image, gallery, best_time, experiences, highlights, rating, elevation, ideal_for, featured, sort_order, published) values
  ('ella', 'Ella', 6.8667, 81.0466, 'Central', 'Uva Province', array['Mountains', 'Adventure', 'Hidden Gems']::text[], 'Where misty mountains, lush tea plantations, and scenic train journeys meet.', 'Nestled in the Central Highlands, Ella is a tranquil mountain village blessed with breathtaking mountain gaps, emerald-green tea estates, cascading waterfalls, and world-renowned hiking trails. The blue train winding across the iconic Nine Arch Bridge is one of the world’s most cinematic travel moments.', 'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&q=80&w=1200', array['https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&q=80&w=800']::text[], 'December – April', array['Nine Arch Bridge Train Watch', 'Ella Rock Sunrise Hike', 'Little Adam’s Peak Trek', 'Ravana Falls Dip & Zip Line']::text[], array['Nine Arch Bridge', 'Ella Rock', 'Ravana Falls', 'Demodara Loop']::text[], 4.9, '1,041 m', array['Hikers', 'Photographers', 'Nature Lovers']::text[], true, 0, true),
  ('sigiriya', 'Sigiriya', 7.957, 80.7603, 'Cultural Triangle', 'Central Province', array['Culture', 'Adventure']::text[], 'An ancient fortress of granite soaring 200 meters above tropical jungle plains.', 'Sigiriya (Lion Rock) is an awe-inspiring UNESCO World Heritage Site featuring 5th-century royal palace ruins, ancient water gardens, delicate frescoes, and the dramatic Lion Gate. Rising abruptly from the jungle canopy, it offers unmatched panoramic views at dawn.', 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&q=80&w=1200', array['https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&q=80&w=800']::text[], 'January – September', array['Sunrise Climb at Pidurangala Rock', 'Exploring Ancient Water Gardens', 'Sigiriya Frescoes Discovery', 'Elephant Safari at Nearby Minneriya']::text[], array['Lion Rock Citadel', 'Frescoes Gallery', 'Mirror Wall', 'Pidurangala Viewpoint']::text[], 4.95, '349 m', array['History Buffs', 'Explorers', 'Culture Seekers']::text[], true, 1, true),
  ('galle', 'Galle Fort', 6.0535, 80.221, 'South', 'Southern Province', array['Culture', 'Beaches', 'Food']::text[], 'Cobblestone streets, Dutch colonial ramparts, boutique cafés, and ocean breezes.', 'Galle Fort is a living historic fortress jutting into the Indian Ocean. Built first by the Portuguese and fortified by the Dutch in the 17th century, today its enclosed streets are lined with chic artisan boutiques, heritage hotels, gemstone galleries, and oceanfront rampart walks.', 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&q=80&w=1200', '{}'::text[], 'November – April', array['Sunset Rampart Walk', 'Dutch Reformed Church Tour', 'Artisan Jewelry & Gem Shopping', 'Seafood Dining in Colonial Courtyards']::text[], array['Galle Lighthouse', 'Dutch Clock Tower', 'Flag Rock', 'Pedlar Street']::text[], 4.88, null, array['Couples', 'Architecture Enthusiasts', 'Foodies']::text[], true, 2, true),
  ('mirissa', 'Mirissa', 5.9483, 80.4578, 'South', 'Southern Province', array['Beaches', 'Wildlife', 'Adventure']::text[], 'Golden crescent beaches, blue whale watching, coconut tree hills, and sunset vibes.', 'Mirissa is the quintessential tropical paradise on Sri Lanka’s south coast. Famed globally for blue whale sightings in the Indian Ocean, Mirissa boasts tranquil sandy bays, surf points, coconut-fringed hills, and lively beachside seafood barbecues under the stars.', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1200', '{}'::text[], 'November – April', array['Blue Whale & Dolphin Safari', 'Coconut Tree Hill Sunset Photo', 'Secret Beach Day Trip', 'Surfing at Mirissa Point']::text[], array['Coconut Tree Hill', 'Secret Beach', 'Parrot Rock', 'Mirissa Harbour']::text[], 4.85, null, array['Beach Lovers', 'Wildlife Safaris', 'Surfers']::text[], true, 3, true),
  ('kandy', 'Kandy', 7.2906, 80.6337, 'Central', 'Central Province', array['Culture', 'Food']::text[], 'The sacred hill capital surrounded by misty forests, lakes, and ancient temples.', 'Kandy was the last royal capital of Sri Lankan kings. Set around a peaceful central lake and framed by tropical mountain ridges, it holds the revered Temple of the Sacred Tooth Relic. Kandy comes alive during the Esala Perahera festival with traditional dancers and torchlit processions.', 'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&q=80&w=1200', '{}'::text[], 'December – April', array['Temple of the Tooth Relic Evening Ceremony', 'Stroll at Royal Botanical Gardens Peradeniya', 'Kandyan Traditional Dance Performance', 'Kandy Lake Serene Sunset Walk']::text[], array['Temple of the Tooth', 'Peradeniya Gardens', 'Kandy Lake', 'Bahirawakanda Buddha']::text[], 4.82, '500 m', array['Culture Seekers', 'Spiritual Travelers', 'Families']::text[], true, 4, true),
  ('jaffna', 'Jaffna', 9.6615, 80.0255, 'North', 'Northern Province', array['Culture', 'Hidden Gems', 'Food']::text[], 'Vibrant Tamil culture, golden kovils, palmyra palms, and untouched northern islands.', 'Jaffna offers a rich, distinct cultural realm in the far north of Sri Lanka. With intricate Hindu temples like Nallur Kandaswamy, historical Dutch forts, shallow blue lagoons, and delicious unique spicy Jaffna crab curry, it is a fascinating haven for authentic explorers.', 'https://images.unsplash.com/photo-1608933221980-dfc7dd884fbf?auto=format&fit=crop&q=80&w=1200', '{}'::text[], 'January – September', array['Nallur Kandaswamy Kovil Blessing', 'Ferried Day Trip to Delft Island Wild Horses', 'Tasting Spicy Jaffna Crab Curry', 'Exploring Jaffna Fort at Sunset']::text[], array['Nallur Kovil', 'Delft Island', 'Jaffna Fort', 'Keerimalai Springs']::text[], 4.78, null, array['Off-the-beaten-path Explorers', 'Cultural Enthusiasts']::text[], true, 5, true),
  ('yala', 'Yala National Park', 6.3725, 81.5168, 'South', 'Southern/Uva Province', array['Wildlife', 'Adventure']::text[], 'The world’s highest density of leopards alongside wild elephants, sloths, and coastal dunes.', 'Yala National Park is Sri Lanka’s premier wilderness sanctuary. Spanning scrub jungles, brackish lagoons, and coastline, Yala is world-famous for elusive Sri Lankan leopards, wild elephant herds, sloth bears, crocodiles, and over 200 bird species.', 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&q=80&w=1200', '{}'::text[], 'February – July', array['Dawn 4x4 Leopard Safari', 'Elephant Herd Tracking', 'Wild Coastal Dune Photography', 'Luxury Glamping Under the Stars']::text[], array['Block 1 Leopard Sanctuary', 'Sithulpawwa Rock Temple', 'Patnanangala Beach']::text[], 4.92, null, array['Wildlife Photographers', 'Safari Seekers', 'Adventurers']::text[], false, 6, true),
  ('nuwara-eliya', 'Nuwara Eliya', 6.9497, 80.7891, 'Central', 'Central Province', array['Mountains', 'Culture', 'Food']::text[], '“Little England” surrounded by rolling tea valleys, colonial country houses, and cool mountain air.', 'Sitting at 1,868 meters elevation, Nuwara Eliya is Sri Lanka’s cool-climate tea capital. Surrounded by terraced Ceylon tea plantations, cascades, golf courses, and Tudor-style colonial villas, it feels like a timeless highland retreat.', 'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&q=80&w=1200', '{}'::text[], 'February – May', array['High Tea at Colonial Grand Hotel', 'Pedro Tea Factory Processing Tour', 'Boating on Gregory Lake', 'Horton Plains World’s End Trek']::text[], array['Gregory Lake', 'Pedro Tea Estate', 'Victoria Park', 'Post Office Heritage']::text[], 4.81, '1,868 m', array['Tea Lovers', 'Highland Escape', 'Relaxation']::text[], false, 7, true),
  ('arugam-bay', 'Arugam Bay', 6.8413, 81.8358, 'East', 'Eastern Province', array['Beaches', 'Adventure', 'Food']::text[], 'World-famous right-hand point breaks, bohemian beach cafes, and wild elephant lagoons.', 'Arugam Bay on the laid-back eastern coast is legendary among international surfers. Known for long point breaks like Main Point and Elephant Rock, Arugam Bay mixes surf culture, beachfront reggae fires, and wildlife safaris in nearby Kumana and Panama.', 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&q=80&w=1200', '{}'::text[], 'May – September', array['Dawn Surf Session at Main Point', 'Lagoon Safari at Pottuvil', 'Sunset at Elephant Rock', 'Beachside Yoga & Healthy Smoothie Bowls']::text[], array['Main Point Surf Break', 'Elephant Rock', 'Pottuvil Lagoon', 'Whiskey Point']::text[], 4.87, null, array['Surfers', 'Backpackers', 'Boho Travelers']::text[], false, 8, true),
  ('trincomalee', 'Trincomalee', 8.5874, 81.2152, 'East', 'Eastern Province', array['Beaches', 'Culture', 'Wildlife']::text[], 'Crystal blue waters, Pigeon Island marine park, cliffside Hindu temples, and blue whales.', 'Trincomalee boasts one of the world’s finest natural deep-water harbors, tranquil white sand beaches at Nilaveli, vibrant coral reefs at Pigeon Island National Park, and the ancient Koneswaram Hindu Temple perching on Swami Rock cliff.', 'https://images.unsplash.com/photo-1512100356356-de1b84283e18?auto=format&fit=crop&q=80&w=1200', '{}'::text[], 'April – October', array['Snorkeling with Blacktip Reef Sharks at Pigeon Island', 'Koneswaram Temple Cliffside Visit', 'Nilaveli Beach Relaxation', 'Whale Watching in Trinco Bay']::text[], array['Pigeon Island', 'Koneswaram Temple', 'Nilaveli Beach', 'Fort Frederick']::text[], 4.86, null, array['Divers & Snorkelers', 'Beach Enthusiasts', 'History Explorers']::text[], false, 9, true),
  ('anuradhapura', 'Anuradhapura', 8.3114, 80.4037, 'Cultural Triangle', 'North Central Province', array['Culture', 'Hidden Gems']::text[], 'Sri Lanka’s sacred first ancient capital with colossal white stupas and a 2,300-year-old sacred fig tree.', 'Anuradhapura was the spiritual and political cradle of ancient Sri Lankan civilization for over 1,300 years. Spanning vast green parklands, its towering bell-shaped stupas rival the Egyptian pyramids in architectural grandeur.', 'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&q=80&w=1200', '{}'::text[], 'May – September', array['Cycling Among Ancient Stupas', 'Paying Homage at Jaya Sri Maha Bodhi Tree', 'Ruwanwelisaya Stupa Evening Illumination', 'Mihintale Sunset Pilgrimage']::text[], array['Ruwanwelisaya', 'Jaya Sri Maha Bodhi', 'Jetavanaramaya', 'Mihintale Rock']::text[], 4.84, null, array['Pilgrims', 'Historians', 'Cyclists']::text[], false, 10, true),
  ('polonnaruwa', 'Polonnaruwa', 7.9403, 81.0188, 'Cultural Triangle', 'North Central Province', array['Culture', 'Adventure']::text[], 'Restored royal palaces, stone-carved Buddha statues, and jungle ruins best explored by bike.', 'Polonnaruwa succeeded Anuradhapura as Sri Lanka’s medieval capital in the 11th century. Remarkably preserved, its archaeological park contains grand audience halls, royal baths, and the breathtaking Gal Vihara—four monumental Buddha images carved into a single granite wall.', 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&q=80&w=1200', '{}'::text[], 'May – September', array['Bicycle Tour of Royal Ruins', 'Gal Vihara Rock Sculpture Admiration', 'Parakrama Samudra Lake Sunset View', 'Monkey Kingdom Wildlife Tour']::text[], array['Gal Vihara', 'Royal Palace of Parakramabahu', 'Vatadage', 'Parakrama Samudra']::text[], 4.83, null, array['Archaeology Lovers', 'Bicycle Explorers']::text[], false, 11, true),
  ('udawalawe', 'Udawalawe National Park', 6.4746, 80.8987, 'South', 'Sabaragamuwa Province', array['Wildlife', 'Adventure']::text[], 'Guaranteed elephant encounters in open savannah landscapes resembling East Africa.', 'Udawalawe is Sri Lanka’s top park for observing wild Sri Lankan elephants in their natural habitat. Centered around a vast reservoir, its grassy grasslands allow close-up observations of wild herds, calves playing, waterbirds, and peacocks.', 'https://images.unsplash.com/photo-1581852017103-68accd5509b6?auto=format&fit=crop&q=80&w=1200', '{}'::text[], 'Year-round (Best Dec – May)', array['Open Jeep Safari for Elephant Herds', 'Visiting Udawalawe Elephant Transit Home', 'Reservoir Sunset Bird Watching']::text[], array['Elephant Herds', 'Udawalawe Reservoir', 'Elephant Transit Home']::text[], 4.89, null, array['Families', 'Animal Lovers', 'Safari Fans']::text[], false, 12, true),
  ('horton-plains', 'Horton Plains & World’s End', 6.8018, 80.8037, 'Central', 'Central Province', array['Mountains', 'Adventure', 'Hidden Gems']::text[], 'Wind-swept misty grasslands ending in a sheer 880-meter vertical drop at World’s End.', 'Sitting on a high altitude plateau over 2,100 meters above sea level, Horton Plains National Park is a unique montane ecosystem of cloud forest, dwarf bamboo, and wild sambar deer, culminating at the terrifying drop of World’s End cliff.', 'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&q=80&w=1200', '{}'::text[], 'January – April (Early mornings)', array['9km Loop Trek to World’s End & Baker’s Falls', 'Spotting Sambar Deer in the Mist', 'Highland Bird Watching']::text[], array['World’s End', 'Baker’s Falls', 'Mini World’s End', 'Chimapani Plain']::text[], 4.86, '2,100 m', array['Trekkers', 'Photographers', 'Highland Explorers']::text[], false, 13, true),
  ('weligama', 'Weligama', 5.9723, 80.4289, 'South', 'Southern Province', array['Beaches', 'Adventure', 'Food']::text[], 'The surf capital for beginners, traditional stilt fishermen, and modern beach clubs.', 'Weligama (meaning Sandy Village) features a vast sheltered bay with gentle, consistent beach break waves ideal for beginner and intermediate surfers. It is also famous for iconic stilt fishermen perched on wooden poles in the sea.', 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&q=80&w=1200', '{}'::text[], 'November – April', array['Beginner Surfing Lessons in Weligama Bay', 'Photographing Traditional Stilt Fishermen', 'Catamaran Sailing & Stand-up Paddleboarding', 'Fresh Catch Seafood Dinners']::text[], array['Weligama Surf Bay', 'Taprobane Island', 'Stilt Fishermen Points']::text[], 4.8, null, array['Beginner Surfers', 'Sunseekers', 'Beach Lifestyle']::text[], false, 14, true),
  ('dambulla', 'Dambulla Cave Temple', 7.8742, 80.6511, 'Cultural Triangle', 'Central Province', array['Culture']::text[], 'Five ancient rock caverns filled with 153 gilded Buddha statues and vibrant ceiling murals.', 'Dambulla Royal Cave Temple is the largest, best-preserved cave temple complex in Sri Lanka. Dating back to the 1st century BCE, five magnificent caves house century-old statues and colorful frescoes painted directly onto the subterranean rock walls.', 'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&q=80&w=1200', '{}'::text[], 'Year-round', array['Exploring 5 Illuminated Sacred Rock Caves', 'Panoramas over Sigiriya Rock from the Summit', 'Golden Temple Museum Tour']::text[], array['Cave of the Divine King', 'Golden Buddha Statue', 'Rock Murals']::text[], 4.81, null, array['Culture Lovers', 'Spiritual Explorers']::text[], false, 15, true),
  ('colombo', 'Colombo', 6.9271, 79.8612, 'West', 'Western Province', array['Culture', 'Food']::text[], 'Sri Lanka’s energetic commercial capital blending colonial charm, glass skyscrapers, and street food.', 'Colombo is a vibrant oceanfront metropolis where colonial British and Dutch architecture stand beside contemporary rooftop bars, bustling Pettah markets, peaceful Buddhist temples on Beira Lake, and oceanfront Galle Face Green promenade.', 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&q=80&w=1200', '{}'::text[], 'December – March', array['Galle Face Green Sunset Street Food Stroll', 'Gangaramaya Temple Visit on Beira Lake', 'Shopping at Dutch Hospital Shopping Precinct', 'Rooftop Cocktail with Indian Ocean Sunset View']::text[], array['Gangaramaya Temple', 'Galle Face Green', 'Pettah Market', 'Lotus Tower']::text[], 4.75, null, array['Urban Explorers', 'Foodies', 'Shoppers']::text[], false, 16, true),
  ('knuckles', 'Knuckles Mountain Range', 7.4583, 80.7917, 'Central', 'Central Province', array['Mountains', 'Adventure', 'Hidden Gems']::text[], 'Unspoiled UNESCO cloud forest wilderness named after its fist-like mountain peaks.', 'The Knuckles Conservation Forest is a rugged bio-diverse haven of cloud forests, hidden waterfalls, endemic wildlife, and isolated traditional mountain hamlets. Perfect for serious trekkers wanting untamed nature.', 'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&q=80&w=1200', '{}'::text[], 'June – September & December – March', array['Multi-day Wilderness Trekking', 'Wild Waterfall Swimming', 'Camping Under Starry Highland Skies', 'Meemure Remote Village Visit']::text[], array['Meemure Village', 'Corbett’s Gap', 'Mini World’s End Knuckles', 'Dunamalix Falls']::text[], 4.91, '1,906 m', array['Advanced Trekkers', 'Eco Travelers', 'Campers']::text[], false, 17, true),
  ('bentota', 'Bentota', 6.4239, 79.9983, 'West', 'Southern Province', array['Beaches', 'Adventure']::text[], 'Luxury beach resorts, golden river lagoons, water sports, and Geoffrey Bawa gardens.', 'Bentota is Sri Lanka’s water sports capital where the tranquil Bentota Ganga river meets the ocean. Known for luxury beachfront resorts, jet-skiing, turtle conservation hatcheries, and Brief Garden designed by Bevis Bawa.', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1200', '{}'::text[], 'November – April', array['Madu River Mangrove Safari', 'Jet Skiing & Banana Boat Watersports', 'Brief Garden Estate Tour', 'Kosgoda Sea Turtle Hatchery Visit']::text[], array['Bentota River Lagoon', 'Brief Garden', 'Kosgoda Turtle Sanctuary']::text[], 4.79, null, array['Families', 'Watersport Fans', 'Resort Travelers']::text[], false, 18, true),
  ('haputale', 'Haputale', 6.7686, 80.9572, 'Central', 'Uva Province', array['Mountains', 'Hidden Gems']::text[], 'High mountain ridge town offering views extending all the way to the southern coastline.', 'Perched on a sheer mountain ledge, Haputale offers dramatic views across Sri Lanka’s southern plains. It is home to Lipton’s Seat—where Sir Thomas Lipton surveyed his vast tea empire—and the serene Adisham Monastery.', 'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&q=80&w=1200', '{}'::text[], 'April – August', array['Lipton’s Seat Viewpoint Sunrise Trek', 'Adisham Benedictine Monastery Visit', 'Diyaluma Waterfall Natural Pool Dip']::text[], array['Lipton’s Seat', 'Adisham Bungalow', 'Diyaluma Falls']::text[], 4.88, '1,431 m', array['Tea Connoisseurs', 'Quiet Mountain Lovers']::text[], false, 19, true)
on conflict (id) do update set
  name = excluded.name,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  region = excluded.region,
  province = excluded.province,
  category = excluded.category,
  short_description = excluded.short_description,
  long_description = excluded.long_description,
  image = excluded.image,
  gallery = excluded.gallery,
  best_time = excluded.best_time,
  experiences = excluded.experiences,
  highlights = excluded.highlights,
  rating = excluded.rating,
  elevation = excluded.elevation,
  ideal_for = excluded.ideal_for,
  featured = excluded.featured,
  sort_order = excluded.sort_order,
  published = excluded.published,
  updated_at = now();

-- 6 row(s) -> public.experience_categories
insert into public.experience_categories (id, title, category, subtitle, image, description, sort_order, published) values
  ('beach-escapes', 'Beach Escapes', 'Beaches', 'Golden sands, turquoise waters & coconut palms', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800', 'Unwind along 1,300+ km of tropical coastline, from southern surf bays to serene eastern white sand beaches.', 0, true),
  ('wild-sri-lanka', 'Wild Sri Lanka', 'Wildlife', 'Leopards, wild elephants & marine giants', 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&q=80&w=800', 'Embark on thrilling 4x4 safaris in Yala & Wilpattu or spot blue whales glinting in the Indian Ocean.', 1, true),
  ('ancient-sri-lanka', 'Ancient Sri Lanka', 'Culture', '2,500 years of royal kingdoms & rock fortresses', 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&q=80&w=800', 'Explore UNESCO rock fortresses, carved stone Buddhas, and sacred stupas towering above jungle plains.', 2, true),
  ('mountain-adventures', 'Mountain Adventures', 'Mountains', 'Misty tea valleys, cloud forests & scenic trains', 'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&q=80&w=800', 'Hike sunrise peaks, ride the famous blue highland train, and swim in natural waterfall pools.', 3, true),
  ('food-and-culture', 'Food & Culture', 'Food', 'Aromatic spices, hopper breakfasts & street feasts', 'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&q=80&w=800', 'Savor fragrant coconut curries, fresh seafood, spicy kottu roti, and world-renowned Ceylon tea.', 4, true),
  ('hidden-sri-lanka', 'Hidden Sri Lanka', 'Hidden Gems', 'Secret waterfalls, remote peaks & island gems', 'https://images.unsplash.com/photo-1608933221980-dfc7dd884fbf?auto=format&fit=crop&q=80&w=800', 'Venture beyond the guidebook to isolated mountain plateaus, wild river canyons, and serene islands.', 5, true)
on conflict (id) do update set
  title = excluded.title,
  category = excluded.category,
  subtitle = excluded.subtitle,
  image = excluded.image,
  description = excluded.description,
  sort_order = excluded.sort_order,
  published = excluded.published,
  updated_at = now();

-- 4 row(s) -> public.featured_experiences
insert into public.featured_experiences (id, title, subtitle, location, duration, category, image, description, highlights, recommended_time, rating, sort_order, published) values
  ('sunrise-ella', 'Sunrise at Ella', 'Watch the mountains wake up above the clouds', 'Ella, Central Highlands', '3–4 Hours', 'Mountains', 'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&q=80&w=1000', 'Rise before dawn and hike up Little Adam’s Peak or Ella Rock as golden sunlight pierces mist floating across emerald tea valleys.', array['360-degree mountain gap panoramas', 'Tea estate walk in morning dew', 'Watch the blue train cross Nine Arch Bridge']::text[], '5:30 AM – 8:30 AM', 4.98, 0, true),
  ('safari-yala', 'Safari in Yala', 'Experience Sri Lanka’s wild side up close', 'Yala National Park', 'Half Day / Full Day', 'Wildlife', 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&q=80&w=1000', 'Navigate dusty jungle tracks in an open-top 4x4 jeep to track elusive Sri Lankan leopards, wild elephant herds, sloth bears, and crocodiles.', array['Highest leopard density in the world', 'Private expert wilderness tracker', 'Wild coastal dune coffee break']::text[], '6:00 AM or 3:00 PM', 4.94, 1, true),
  ('sunset-mirissa', 'Sunset in Mirissa', 'Golden beaches and unforgettable ocean sunsets', 'Mirissa, South Coast', '2–3 Hours', 'Beaches', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1000', 'Climb Coconut Tree Hill as the sun dips into the Indian Ocean, painting the palm fronds and crashing waves in fiery violet and amber hues.', array['Iconic Coconut Tree Hill viewpoint', 'Fresh grilled catch of the day at beachside cafes', 'Calm turquoise bay swimming']::text[], '5:00 PM – 7:00 PM', 4.92, 2, true),
  ('walk-galle-fort', 'Walk Through Galle Fort', 'Discover colonial architecture, cafés and stories', 'Galle Fort, South Coast', '2–3 Hours', 'Culture', 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&q=80&w=1000', 'Wander cobblestone lanes enclosed by 400-year-old Dutch ramparts, visiting artisan jewelers, boutique espresso bars, and historic lighthouses.', array['Guided rampart heritage walk at golden hour', 'Artisan gem & spiced tea shopping', 'Colonial courtyard gourmet dining']::text[], '4:00 PM – 7:00 PM', 4.9, 3, true)
on conflict (id) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  location = excluded.location,
  duration = excluded.duration,
  category = excluded.category,
  image = excluded.image,
  description = excluded.description,
  highlights = excluded.highlights,
  recommended_time = excluded.recommended_time,
  rating = excluded.rating,
  sort_order = excluded.sort_order,
  published = excluded.published,
  updated_at = now();

-- 4 row(s) -> public.tours
insert into public.tours (id, title, subtitle, days, route, short_desc, full_desc, image, highlights, included_places, price_from, category, itinerary, sort_order, published) values
  ('island-in-7-days', 'Island in 7 Days', 'The essential Sri Lanka journey combining culture, mountains, wildlife & beach.', 7, array['Colombo', 'Kandy', 'Ella', 'Yala', 'South Coast']::text[], 'Experience the magical highlights of Sri Lanka in one week—from sacred hill capitals and scenic train journeys to leopard safaris and tropical beach sunsets.', 'Curated for travelers seeking the ultimate introduction to Sri Lanka, this signature 7-day expedition spans the vibrant island across five distinct landscapes.', 'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&q=80&w=1200', array['Temple of the Tooth ceremonial blessing in Kandy', 'Iconic scenic blue train ride through Ella tea plantations', 'Private 4x4 leopard safari in Yala National Park', 'Sunset rampart stroll at historic Galle Fort']::text[], array['Colombo', 'Kandy', 'Nuwara Eliya', 'Ella', 'Yala', 'Mirissa', 'Galle']::text[], 1250, 'Full Island', '[{"day":1,"title":"Arrival & Colombo Gateway","description":"Private airport greeting, boutique hotel check-in, and sunset cocktails overlooking Galle Face Green.","location":"Colombo"},{"day":2,"title":"Journey to Kandy Hill Capital","description":"Scenic drive into the mountains, visit Peradeniya Botanical Gardens and Temple of the Tooth Relic.","location":"Kandy"},{"day":3,"title":"The Highland Blue Train to Ella","description":"Board the world-famous highland blue train winding through tea estates and misty mountain gaps.","location":"Ella"},{"day":4,"title":"Ella Peaks & Waterfall Discovery","description":"Sunrise hike to Little Adam’s Peak, photo stop at Nine Arch Bridge, and Ravana Falls.","location":"Ella"},{"day":5,"title":"Wild Safari in Yala","description":"Descend to southern plains for an afternoon 4x4 jeep safari tracking leopards and wild elephants.","location":"Yala"},{"day":6,"title":"South Coast Beach Relaxation","description":"Coastal drive to Mirissa & Galle, Coconut Tree Hill sunset photo and beachside seafood banquet.","location":"Mirissa / Galle"},{"day":7,"title":"Galle Fort Heritage & Farewell","description":"Morning guided walk through Dutch colonial ramparts before coastal highway return to Colombo airport.","location":"Galle / Colombo"}]'::jsonb, 0, true),
  ('cultural-sri-lanka', 'Cultural Sri Lanka', 'Immerse yourself in 2,500 years of royal heritage and sacred architecture.', 6, array['Anuradhapura', 'Sigiriya', 'Dambulla', 'Kandy']::text[], 'Step back in time as you explore ancient rock fortresses, subterranean cave temples, ruined royal palaces, and sacred Buddhist monuments.', 'An enchanting voyage through Sri Lanka’s UNESCO World Heritage Cultural Triangle, designed for lovers of history, art, and timeless spiritual traditions.', 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&q=80&w=1200', array['Dawn climb of the majestic Sigiriya Lion Rock Fortress', 'Bicycle tour through Anuradhapura ancient royal stupas', 'Dambulla gilded rock cave temples exploration', 'Kandyan traditional drum and dance cultural show']::text[], array['Anuradhapura', 'Polonnaruwa', 'Sigiriya', 'Dambulla', 'Kandy']::text[], 1100, 'Culture', '[{"day":1,"title":"Arrival & Sacred Anuradhapura","description":"Drive to Sri Lanka’s 1st ancient capital and visit the 2,300-year-old sacred Sri Maha Bodhi tree.","location":"Anuradhapura"},{"day":2,"title":"Medieval Ruins of Polonnaruwa","description":"Cycle past royal palaces, audience halls, and the carved granite Buddhas of Gal Vihara.","location":"Polonnaruwa"},{"day":3,"title":"Sigiriya Lion Rock Sunrise","description":"Scale the 200m granite citadel of Sigiriya before crowds arrive, exploring royal water gardens.","location":"Sigiriya"},{"day":4,"title":"Dambulla Cave Temples","description":"Ascend to 5 illuminated rock caverns filled with ancient frescoes and gilded Buddha statues.","location":"Dambulla"},{"day":5,"title":"Kandy Royal Kingdom","description":"Discover Kandy lake, traditional artisan workshops, and evening Temple of the Tooth ceremony.","location":"Kandy"},{"day":6,"title":"Spice Gardens & Departure","description":"Morning herbal spice garden tour and private transfer back to Colombo airport.","location":"Colombo"}]'::jsonb, 1, true),
  ('wild-sri-lanka', 'Wild Sri Lanka Expedition', 'An epic wildlife safari from dense jungles to elephant gatherings.', 8, array['Wilpattu', 'Sigiriya', 'Minneriya', 'Yala']::text[], 'A paradise for wildlife lovers. Track leopards, sloth bears, wild elephant herds, saltwater crocodiles, and blue whales across national sanctuaries.', 'Sri Lanka is Asia’s top biodiversity hotspot. This expedition brings you face-to-face with the island’s Big Five: Leopard, Elephant, Sloth Bear, Blue Whale, and Sperm Whale.', 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&q=80&w=1200', array['Wilpattu National Park natural lake safari', 'Witness the Elephant Gathering at Minneriya Reservoir', 'Yala National Park dawn leopard tracking safari', 'Whale watching cruise off the southern coast']::text[], array['Wilpattu', 'Sigiriya', 'Minneriya', 'Udawalawe', 'Yala', 'Mirissa']::text[], 1480, 'Wildlife', '[{"day":1,"title":"Arrival & Wilpattu Wilderness","description":"Head north to Sri Lanka’s largest and quietest national park, famous for natural lakes.","location":"Wilpattu"},{"day":2,"title":"Full Day Wilpattu Safari","description":"Track elusive leopards and sloth bears through dense dry zone evergreen forests.","location":"Wilpattu"},{"day":3,"title":"Sigiriya & Minneriya Elephants","description":"Climb Pidurangala rock at sunrise, followed by an afternoon jeep safari watching wild elephant herds.","location":"Minneriya"},{"day":4,"title":"Scenic Countryside Drive South","description":"Travel through rubber and spice plantations to Udawalawe National Park edge.","location":"Udawalawe"},{"day":5,"title":"Udawalawe Elephant Sanctuary","description":"Morning safari witnessing wild elephant herds and visiting the Elephant Transit Home.","location":"Udawalawe"},{"day":6,"title":"Yala Leopard Territory","description":"Check into luxury safari tented camp near Yala and embark on afternoon 4x4 game drive.","location":"Yala"},{"day":7,"title":"Ocean Safari in Mirissa","description":"Early morning ocean vessel excursion to view giant blue whales and playful dolphin pods.","location":"Mirissa"},{"day":8,"title":"Coastal Farewell","description":"Relaxed beach breakfast and highway transfer to airport.","location":"Colombo"}]'::jsonb, 2, true),
  ('southern-escape', 'Southern Coastal Escape', 'Sun-drenched beaches, surf bays, colonial fort heritage & ocean breezes.', 5, array['Galle', 'Unawatuna', 'Weligama', 'Mirissa']::text[], 'Unwind along Sri Lanka’s golden southern shore. Enjoy boutique luxury, seafood gastronomy, surf points, and tranquil sunset bays.', 'The ultimate coastal getaway combining luxury beachfront living, heritage strolls inside Galle Fort, wellness spa treatments, and ocean sunsets.', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1200', array['Private boutique villa accommodation on the beach', 'Guided culinary street food and seafood market tour', 'Catamaran sunset sailing along Mirissa coast', 'Surf coaching or paddleboarding in Weligama Bay']::text[], array['Galle', 'Unawatuna', 'Weligama', 'Mirissa', 'Bentota']::text[], 950, 'Luxury', '[{"day":1,"title":"Arrival at Galle Coast","description":"Express highway transfer to UNESCO Galle Fort. Evening rampart walk and welcome dinner.","location":"Galle Fort"},{"day":2,"title":"Unawatuna Bay & Jungle Beach","description":"Beach day at pristine Unawatuna bay, Japanese Peace Pagoda visit, and oceanfront dining.","location":"Unawatuna"},{"day":3,"title":"Weligama Surf & Stilt Fishermen","description":"Morning surf session or stilt fishermen photography, afternoon herbal spa rejuvenation.","location":"Weligama"},{"day":4,"title":"Mirissa Coconut Hill & Catamaran","description":"Coconut Tree Hill sunrise photo shoot and private sunset catamaran cruise with drinks.","location":"Mirissa"},{"day":5,"title":"Bentota Lagoon & Departure","description":"Madu River mangrove boat safari on the way back to Colombo airport.","location":"Bentota / Colombo"}]'::jsonb, 3, true)
on conflict (id) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  days = excluded.days,
  route = excluded.route,
  short_desc = excluded.short_desc,
  full_desc = excluded.full_desc,
  image = excluded.image,
  highlights = excluded.highlights,
  included_places = excluded.included_places,
  price_from = excluded.price_from,
  category = excluded.category,
  itinerary = excluded.itinerary,
  sort_order = excluded.sort_order,
  published = excluded.published,
  updated_at = now();

-- 6 row(s) -> public.articles
insert into public.articles (id, title, category, published_at, read_time, image, snippet, author_name, author_avatar, author_role, content, sort_order, published) values
  ('sunrise-locations-sri-lanka', '10 Places to Watch Sunrise in Sri Lanka', 'INSPIRATION', '2026-02-12', '6 min read', 'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&q=80&w=800', 'From the peaks of Adam’s Peak to the silent shores of Trincomalee, discover where morning light transforms the island into liquid gold.', 'Nishan Fernando', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200', 'Lead Explorer', array['There is a quiet magic to Sri Lankan mornings. Long before the island awakens, clouds gather in violet valleys and fishing catamarans cut through silent sea mist.', '1. Little Adam’s Peak, Ella: A gentle 45-minute climb rewarded by 360-degree views of morning light spilling over Ella Gap.', '2. Pidurangala Rock, Sigiriya: The ultimate viewpoint to watch the sun rise directly behind the ancient Lion Rock fortress.', '3. Swami Rock, Trincomalee: Perch high on the eastern cliffs as devotional prayers echo from Koneswaram Temple into the dawn sky.', '4. World’s End, Horton Plains: Arrive by 6:00 AM before clouds cover the sheer 880m vertical cliff drop.']::text[], 0, true),
  ('ultimate-ella-guide', 'The Ultimate Ella Travel Guide: Mountains, Trains & Tea', 'DESTINATION GUIDES', '2026-01-28', '8 min read', 'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&q=80&w=800', 'Everything you need to know about hiking Ella Rock, capturing Nine Arch Bridge, finding secret waterfalls, and enjoying mountain cafe culture.', 'Dilini Senanayake', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200', 'Cultural Historian', array['Ella has evolved from a sleepy railway stop into the crown jewel of Sri Lanka’s highlands. At an elevation of 1,041 meters, the air is crisp, the tea is fresh, and every trail leads to breathtaking vistas.', 'How to catch the train over Nine Arch Bridge: The blue passenger train passes approximately 6 times daily. Arrive 30 minutes early to secure a spot along the tea estate slopes.', 'Hike Ella Rock: A 4-hour return trek starting along train tracks before ascending through rubber trees and eucalyptus groves.', 'Where to eat: Enjoy organic farm-to-table dining, spiced iced chais, and fresh roti in cozy hillside spots.']::text[], 1, true),
  ('best-beaches-sri-lanka', 'Best Beaches in Sri Lanka: From Surf Points to Secret Bays', 'COASTAL', '2026-01-15', '7 min read', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800', 'Whether you want world-class waves, serene palm fringed bays, or blue whale excursions, here is your definitive beach roadmap.', 'Kavinda Perera', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200', 'Surf & Ocean Guide', array['With over 1,300 kilometers of tropical coastline, Sri Lanka is a year-round beach haven thanks to its dual monsoon seasons.', 'South Coast (Best Nov - Apr): Hiriketiya for surf and horseshoe bay vibes, Mirissa for sunsets and whales, Tangalle for untouched quiet beaches.', 'East Coast (Best May - Sep): Nilaveli for powdery white sand, Arugam Bay for world-renowned right-hand point breaks, Pasikuda for shallow calm turquoise lagoons.']::text[], 2, true),
  ('guide-sri-lankan-food', 'A Guide to Sri Lankan Food: Curries, Hoppers & Spices', 'CULINARY', '2025-12-20', '5 min read', 'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&q=80&w=800', 'Unpack the rich flavors of Ceylon cinnamon, toasted coconut, clay-pot fish curry, crispy egg hoppers, and spicy kottu roti.', 'Anushka Jaywardena', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200', 'Culinary Curator', array['Sri Lankan cuisine is a complex celebration of roasted spices, fresh coconut milk, curry leaves, pandan, and tropical heat.', 'Must-try dishes:', '• Egg Hoppers (Appa): Bowl-shaped fermented rice flour crêpes with a soft-boiled egg in the center.', '• Kottu Roti: Shredded flatbread flash-fried on a flat iron griddle with vegetables, egg, spices, and chicken or seafood.', '• Black Pork Curry: Tender pork slow-braised with dark-roasted spices and goraka (garcinia).']::text[], 3, true),
  ('wildlife-safaris-where-to-go', 'Wildlife Safaris: Where to Go for Leopards, Elephants & Whales', 'WILDLIFE', '2025-12-05', '9 min read', 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&q=80&w=800', 'Navigating Sri Lanka’s 26 national parks to plan the perfect safari journey for every season.', 'Nishan Fernando', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200', 'Lead Explorer', array['Sri Lanka packs more wildlife diversity per square kilometer than almost any country in Asia.', 'Yala: Best for elusive leopards and sloth bears.', 'Minneriya & Kaudulla: Home to "The Gathering"—up to 300 Asian elephants assembling around reservoir shores.', 'Wilpattu: Dense jungle & tranquil lakes with fewer safari crowds.']::text[], 4, true),
  ('hidden-gems-visit', 'Hidden Gems You Should Visit Before Everyone Else Does', 'OFF THE BEATEN PATH', '2025-11-18', '6 min read', 'https://images.unsplash.com/photo-1608933221980-dfc7dd884fbf?auto=format&fit=crop&q=80&w=800', 'Step off the main tourist trail to explore secret cloud forests, ancient cave sanctuaries, and wild island archipelagos.', 'Dilini Senanayake', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200', 'Cultural Historian', array['Beyond the iconic Sigiriya and Ella lies a secret Sri Lanka preserved in quiet valleys and untouched coastlines.', 'Discover Riverston in the Knuckles, boat safaris in Gal Oya, and wild horses galloping on Delft Island.']::text[], 5, true)
on conflict (id) do update set
  title = excluded.title,
  category = excluded.category,
  published_at = excluded.published_at,
  read_time = excluded.read_time,
  image = excluded.image,
  snippet = excluded.snippet,
  author_name = excluded.author_name,
  author_avatar = excluded.author_avatar,
  author_role = excluded.author_role,
  content = excluded.content,
  sort_order = excluded.sort_order,
  published = excluded.published,
  updated_at = now();

-- 8 row(s) -> public.hidden_gems
insert into public.hidden_gems (id, name, region, image, description, why_visit, tag, sort_order, published) values
  ('riverston', 'Riverston Peak & Pitawala Pathana', 'Central Highlands', 'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&q=80&w=800', 'A breezy high-altitude plateau in the Knuckles range featuring dramatic mini World’s End precipices and wind-swept cloud forests.', 'Fewer tourists, misty mountain gaps, and pristine trekking trails.', 'Cloud Forest Peak', 0, true),
  ('gal-oya', 'Gal Oya National Park', 'Eastern Wilderness', 'https://images.unsplash.com/photo-1581852017103-68accd5509b6?auto=format&fit=crop&q=80&w=800', 'The only national park in Sri Lanka where you can take a boat safari to watch wild elephants swimming between reservoir islands.', 'Swimming elephants, boat safaris & Vedda indigenous walks.', 'Boat Safari Haven', 1, true),
  ('delft-island', 'Delft Island (Neduntheevu)', 'Far North', 'https://images.unsplash.com/photo-1608933221980-dfc7dd884fbf?auto=format&fit=crop&q=80&w=800', 'A remote coral-fringed island off Jaffna inhabited by wild ponies descended from Dutch colonial horses and coral walls.', 'Wild horses, baobab trees & ancient Portuguese coral ruins.', 'Wild Pony Island', 2, true),
  ('belilena', 'Belilena Prehistoric Cave', 'Sabaragamuwa', 'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&q=80&w=800', 'A cavern hidden behind a waterfall where 30,000-year-old human fossils of Balangoda Man were discovered in deep jungle.', 'Prehistoric anthropology & waterfall cave hiking.', 'Prehistoric Cave', 3, true),
  ('bambarakanda', 'Bambarakanda Waterfall', 'Uva Province', 'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&q=80&w=800', 'Sri Lanka’s highest waterfall, plummeting 263 meters through pine forests into a cold mountain basin.', 'Tallest waterfall in Sri Lanka surrounded by pine woods.', 'Tallest Waterfall', 4, true),
  ('madulsima', 'Madulsima Mini World’s End', 'Passara Ridge', 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&q=80&w=800', 'A dizzying ridge drop over 1,000 meters above eastern tea valleys, where clouds roll right beneath your feet.', 'Sea of clouds, cliffside camping & spectacular vistas.', 'Sea of Clouds Ridge', 5, true),
  ('kudumbigala', 'Kudumbigala Monastery', 'Eastern Jungle', 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&q=80&w=800', 'An ancient rock monastery dating back to 246 BCE, surrounded by wildlife sanctuary wilderness near Arugam Bay.', 'Cylindrical stupa, jungle tranquility & ocean views.', 'Rock Monastery Sanctuary', 6, true),
  ('kalpitiya', 'Kalpitiya Peninsula', 'North West Coast', 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&q=80&w=800', 'A windy coastal strip separating lagoon and sea, world-famous for kitesurfing and dolphin pods in the thousands.', 'Kitesurfing, spinner dolphin pods & pristine sandbars.', 'Kitesurf & Dolphin Haven', 7, true)
on conflict (id) do update set
  name = excluded.name,
  region = excluded.region,
  image = excluded.image,
  description = excluded.description,
  why_visit = excluded.why_visit,
  tag = excluded.tag,
  sort_order = excluded.sort_order,
  published = excluded.published,
  updated_at = now();

-- 8 row(s) -> public.photo_stories
insert into public.photo_stories (id, title, location, category, image, caption, aspect, sort_order, published) values
  ('p1', 'Highland Mist & Blue Trains', 'Ella & Nuwara Eliya', 'Highlands', 'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&q=80&w=800', 'The legendary highland express winding across mountain viaducts through morning fog.', 'portrait', 0, true),
  ('p2', 'The Golden Lion Rock', 'Sigiriya', 'Heritage', 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&q=80&w=800', 'An ancient granite palace fortress rising 200m above the jungle canopy at sunrise.', 'landscape', 1, true),
  ('p3', 'South Coast Sunset Glow', 'Mirissa', 'Beaches', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800', 'Swaying coconut palms against fiery amber and magenta ocean skies.', 'portrait', 2, true),
  ('p4', 'Jungle Monarch', 'Yala National Park', 'Wildlife', 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&q=80&w=800', 'A Sri Lankan leopard resting upon a sun-warmed granite outcrop in Yala.', 'square', 3, true),
  ('p5', 'Colonial Ramparts at Dusk', 'Galle Fort', 'Architecture', 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&q=80&w=800', 'Waves crashing against 17th-century Dutch stone bastions as dusk settles.', 'landscape', 4, true),
  ('p6', 'Emerald Tea Pluckers', 'Hatton Tea Valleys', 'Culture', 'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&q=80&w=800', 'Hand-harvesting delicate two leaves and a bud in Ceylon’s legendary highland estates.', 'portrait', 5, true),
  ('p7', 'Stilt Fishermen at Dawn', 'Koggala & Weligama', 'Tradition', 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&q=80&w=800', 'Ancient fishing artistry balancing gracefully on wooden poles set in crashing tides.', 'landscape', 6, true),
  ('p8', 'Northern Temple Glow', 'Jaffna', 'Culture', 'https://images.unsplash.com/photo-1608933221980-dfc7dd884fbf?auto=format&fit=crop&q=80&w=800', 'Golden gopurams of Nallur Kovil lit during evening incense rituals.', 'square', 7, true)
on conflict (id) do update set
  title = excluded.title,
  location = excluded.location,
  category = excluded.category,
  image = excluded.image,
  caption = excluded.caption,
  aspect = excluded.aspect,
  sort_order = excluded.sort_order,
  published = excluded.published,
  updated_at = now();

-- 3 row(s) -> public.hero_slides
insert into public.hero_slides (id, image, title, caption, sort_order, published) values
  ('ella-highlands', 'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&q=80&w=2000', 'Ella Central Highlands', 'Misty Mountains & Tea Valleys', 0, true),
  ('sigiriya-citadel', 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&q=80&w=2000', 'Sigiriya Ancient Rock Citadel', '2,500 Years of Sacred History', 1, true),
  ('mirissa-shoreline', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=2000', 'Mirissa Palm Shoreline', 'Indian Ocean Sunset Bay', 2, true)
on conflict (id) do update set
  image = excluded.image,
  title = excluded.title,
  caption = excluded.caption,
  sort_order = excluded.sort_order,
  published = excluded.published,
  updated_at = now();

-- 4 row(s) -> public.pillars
insert into public.pillars (id, icon, title, description, sort_order, published) values
  ('local-knowledge', 'Users', 'Local Knowledge', 'Discover Sri Lanka through the eyes of island natives who possess deep generational heritage, secret trails, and insider connections.', 0, true),
  ('authentic-experiences', 'Compass', 'Authentic Experiences', 'Go beyond predictable tourist hotspots. Access secluded waterfalls, ancestral spice gardens, and private cultural encounters.', 1, true),
  ('flexible-journeys', 'Sliders', 'Flexible Journeys', 'Build every day around your rhythm and curiosity—from high-energy mountain climbs to unhurried beach stays.', 2, true),
  ('responsible-travel', 'Leaf', 'Responsible Travel', 'Explore while actively respecting wildlife habitats, conserving fragile ecosystems, and empowering rural island communities.', 3, true)
on conflict (id) do update set
  icon = excluded.icon,
  title = excluded.title,
  description = excluded.description,
  sort_order = excluded.sort_order,
  published = excluded.published,
  updated_at = now();

commit;
